CREATE TABLE TAXI_LOCATIONS (
    TAXI_ID         INT               NOT NULL,
    RECORD_TIME     TIMESTAMP         NOT NULL,
    TAXI_LOCATION   GEOGRAPHY_POINT   NOT NULL
);
PARTITION TABLE TAXI_LOCATIONS ON COLUMN TAXI_ID;

CREATE TABLE REGIONS (
    REGION_ID         INT              NOT NULL  PRIMARY KEY,
    REGION_BOUNDARY   GEOGRAPHY(1024)  NOT NULL
);
CREATE INDEX REGIONS_IDX ON REGIONS(REGION_BOUNDARY);

CREATE VIEW REGIONAL_TAXI_COUNT (DAY, HOUR, REGION_ID, TAXI_COUNT) AS
SELECT EXTRACT(DAY FROM TAXI_LOCATIONS.RECORD_TIME) AS DAY,
       EXTRACT(HOUR FROM TAXI_LOCATIONS.RECORD_TIME) AS HOUR,
       REGIONS.REGION_ID,
       COUNT(*) FROM REGIONS JOIN TAXI_LOCATIONS ON
    CONTAINS(REGIONS.REGION_BOUNDARY, TAXI_LOCATIONS.TAXI_LOCATION)
GROUP BY DAY, HOUR, REGIONS.REGION_ID;

CREATE PROCEDURE InsertTaxiLocation
PARTITION ON TABLE TAXI_LOCATIONS COLUMN TAXI_ID AS
INSERT INTO TAXI_LOCATIONS VALUES (?,?,
    POINTFROMTEXT(CONCAT('POINT(',CAST(? AS VARCHAR),' ',CAST(? AS VARCHAR),')')));
